### ISSUE TITLE
filterMap and filter

### ISSUE THREAD

**Issue by jvoigtlaender** [Apanatshka/elm-signal-extra#10]
Maybe `Signal.Extra.filterMap` can now be dropped, given that Elm-0.15 comes with `Signal.filterMap`? Then, `Signal.Extra.filter` could be defined via `Signal.filterMap identity`.

**Comment by Apanatshka** [comment]
Yes, it can be dropped. There's no hurry though. I want to make a forward-compatible Stream library based on `type Stream a = Signal (Maybe a)`. I think I'll remove `Signal.Extra.filterMap` along with that change. I might have time to work on all of this next week.

**Comment by Apanatshka** [comment]
I've just defined the `Signal.Stream` module based on the [commit](https://github.com/elm-lang/core/commit/ec22bcc4818d2e806d80107d94060394392856fe) [you linked to](https://github.com/elm-lang/core/pull/209#issuecomment-97752669). 
I've also removed `Signal.Extra.filterMap` and defined `Signal.Extra.filter` in terms of `Signal.filterMap`. Are there any other "MAJOR" changes that you know of?

**Comment by jvoigtlaender** [comment]
I'm not aware of other changes to the `core` API that would motivate a change in this library here (if that was the question).

**Comment by Apanatshka** [comment]
Yes that was the question, I see I phrased that rather cryptically.. Thanks, then I'll be releasing version 5.0.0.
