### ISSUE TITLE
Could not find module `Signal.Fun`

### ISSUE THREAD

**Issue by jafrog** [Apanatshka/elm-signal-extra#13]
I get this error on version 5.2.0:

```
Error when searching for modules exposed by elm-package.json:
   Could not find module 'Signal.Fun'
```

I noticed `Signal.Fun` is listed in exposed modules in `elm-package.json` but there's no declaration of this module in `src/`. Missing file? 5.1.1 works fine.

**Comment by Apanatshka** [comment]
Yes, missing file, sorry about that! I'll probably have time to fix that in about 10 hours from now. 
I also opened an [issue on elm-package](https://github.com/elm-lang/elm-package/issues/114).

**Comment by Apanatshka** [comment]
[fixed](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.1/)
