### ISSUE TITLE
Possible new function ... deltas : a -> Signal a -> Signal (a, a)

### ISSUE THREAD

**Issue by rgrempel** [Apanatshka/elm-signal-extra#20]
I've got a little function that might fit well here. Conceptually, it's like `runBuffer`, except it's always just a tuple2 -- that is, a delta of the current value and the previous value.

Here's the function:

``` elm
deltas : a -> Signal a -> Signal (a, a)
deltas initial signal =
    let
        step current delta = (snd delta, current)

    in
        Signal.foldp step (initial, initial) signal
```

Of course, you could achieve something very similar with `runBuffer`, but conceptually what I needed was a delta, so I wrote this instead.

Anyway, I thought I'd offer it up -- if you're interested, let me know and I can do up a proper pull request. It's fine if you're not interested -- it is, after all, very similar to `runBuffer`.

**Comment by Apanatshka** [comment]
Thanks for the offer. It's indeed very similar to `runBuffer`. But I don't know, perhaps it's a useful most common use case of a buffer. 

The issue with adding this to the package is that there are a number of variants based on initial value. You've opted for the input value, duplicated. You could also have the initial value of the signal, duplicated. Or have one of the values as the initial value from the signal and the other one user-supplied. But those can be in two orders. So that's 4 different, possibly useful versions...

**Comment by rgrempel** [comment]
Yes, initial values are a bit of a pain!

Is there a way to get the actual initial value of the Signal from the Signal itself? If I had a choice, I'd actually prefer:

``` elm
deltas : Signal a -> Signal (a, a)
```

But I'm not sure how to do that ... the `foldp` needs an initial tuple ... wait just a second ... it might be possible with our friend `foldp'` -- I'll look into that.

**Comment by Apanatshka** [comment]
Should be possible with `foldp'`. Maybe the most general way to do this is the nicest?

``` elm
deltas : (a -> (a,a)) -> Signal a -> Signal (a, a)
```

**Comment by rgrempel** [comment]
Yes, `foldp'` does it ... here's what I came up with:

``` elm
deltas : Signal a -> Signal (a, a)
deltas signal =
    let
        step value delta =
            (snd delta, value)

        initial value =
            (value, value)

    in
        foldp' step initial signal
```

I sort of like the simplicity of just having one parameter. And, I'm not actually sure what the meaning of any other `a -> (a, a)` would be -- anything other than the actual initial value seems arbitrary.

I suppose one could have two versions ...

``` elm
deltas : Signal a -> Signal (a, a)

deltas' : (a -> (a,a)) -> Signal a -> Signal (a, a)
```

Since, as you say, you can implement any version of an initial value with `deltas'`, but `deltas` seems like the most sensible approach.

**Comment by Apanatshka** [comment]
You're right, I'm overgeneralising. 
If you're willing to write the docs for `deltas : Signal a -> Signal (a, a)` I'm willing to press that merge button ;)
