### ISSUE TITLE
Updating for Elm 0.16

### ISSUE THREAD

**Issue by rgrempel** [Apanatshka/elm-signal-extra#22]
Let me know if you'd like any help updating for Elm 0.16 -- I'd be happy to contribute, but don't want to step on what you'll be doing.

**Comment by Apanatshka** [comment]
I didn't start on it yet. So I will welcome a PR :)

**Comment by rgrempel** [comment]
Here's a PR: #23 

One question is whether you actually want to provide `(~)` and `(<~)` now that they've been removed from `Signal`. I have added them in this PR. My thinking is that it might be helpful to some people in transitioning code (e.g. just monkey with imports and you don't have to touch the actual code). But, of course, we could leave them out instead.

**Comment by Apanatshka** [comment]
I like the operators, so that's fine. I would be ok with not including them if the core libraries were trying to discourage operators by providing `andMap` instead of `(~)`. Since that's not the case, let's provide the operators.
