### ISSUE TITLE
Polling a task to create a signal

### ISSUE THREAD

**Issue by rgrempel** [Apanatshka/elm-signal-extra#26]
I've got an idea for a function that would look like this:

``` elm
{-| Given an incoming signal, and function which might produce a Task,
perform the Task whenever the incoming signal fires, and send the
result of the Task to a new signal.
-}
poll : Signal a -> (a -> Maybe(Task x b)) -> Signal (Maybe (Result x b))
```

Here's some context for it:

https://github.com/rgrempel/elm-web-api/issues/4

Does that sound interesting to you? I haven't written it yet, but I think it should be possible.

**Comment by rgrempel** [comment]
Actually, thinking about this a moment longer, the trick would be to actually get the Tasks performed -- I'd have to also return a `Signal Task` so that it can be sent to a port.

So, one option would be:

``` elm
poll : Signal a -> (a -> Maybe(Task x b)) -> (Signal (Task () ()), Signal (Maybe (Result x b)))
```

... with the instructions that the first returned signal needs to be sent to a port, and the second one is the one with the results.

Or, it would be possible to set up a global `Signal (Task () ())` in the module, with instructions that that needs to be sent to a port.

But both of those seem potentially a little over-elaborate -- perhaps this is the sort of thing that it's easier for people to just do themselves, rather than have a library function for?

**Comment by Apanatshka** [comment]
Yeah, I think this is a too complicated function.. You could simplify it with Native code, but I don't want to go there in this library if I don't have to.

**Comment by rgrempel** [comment]
Makes sense to me.
