### ISSUE TITLE
Feature suggestion: filterFold

### ISSUE THREAD

**Issue by imeckler** [Apanatshka/elm-signal-extra#5]
Is there any interest in including the following function `filterFold`? It keeps popping up in my `Utils` modules.

``` elm
filterFold : (a -> b -> Maybe b) -> b -> Signal a -> Signal b
filterFold f z s =
  Signal.foldp (\a (b,keep) -> case f a b of
    Just b' -> (b', True)
    Nothing -> (b, False))
    (z, True) s
  |> Signal.keepIf snd (z, True)
  |> Signal.map fst
```

The argument `f` allows us to indicate if we don't want to update the value in the `foldp` signal. At any time, the two signals `foldp (\a b -> Maybe.withDefault b (f a b)) z s` and `filterFold f z s` have the same value, but the latter updates less often (it doesn't update when `f` returns `Nothing` whereas the first does). It also generalizes `filterMap`.

``` elm
filterMap : (a -> Maybe b) -> b -> Signal a -> Signal b
filterMap f y = filterFold (\x _ -> f x) y
```

**Comment by Apanatshka** [comment]
Looks useful. Can you give some examples where you use `filterFold`?

**Comment by Apanatshka** [comment]
If it was a `(a -> Maybe (b -> b))`, the implementation would have been easier:

``` elm
filterFold : (a -> Maybe (b -> b)) -> b -> Signal a -> Signal b
filterFold f initial input = filterMap f identity input |> foldp (<|) initial
```

But I guess, that makes it less general.

**Comment by Apanatshka** [comment]
Ok, that's `filterFold` implemented. Can you check that it's the same semantics as you meant? Check the master branch, not the commit referring this issues, that one didn't compile :sweat_smile:

**Comment by imeckler** [comment]
I believe it is.
