### ISSUE TITLE
Version on packages.elm-lang.org is missing elm-version declaration

### ISSUE THREAD

**Issue by Morendil** [Apanatshka/elm-signal-extra#8]
Resulting in:

```
elm-package install

Error: Unable to get elm-package.json for Apanatshka/elm-signal-extra 3.3.1
Missing field "elm-version", acceptable versions of the Elm Platform (e.g. "0.15.0 <= v < 0.16.0").
    Check out an example elm-package.json file here:
    <https://raw.githubusercontent.com/evancz/elm-html/master/elm-package.json>
```

**Comment by Apanatshka** [comment]
I think that's the standard message Elm 0.15 elm-package will give you when a package is not yet updated to 0.15. I'm in the middle of updating it ;)

**Comment by Apanatshka** [comment]
Ok, updated to 0.15. Use the new `3.4.0` version. If your problem persists, let me know.

**Comment by Morendil** [comment]
Thanks! It wasn't clear whether the package had already been updated to 0.15 - the most recent commit referred to updating _for_ 0.15. I'll give it a spin.
